services:
  - type: web
    name: social-media-api
    env: python
    plan: starter
    buildCommand: |
      apt-get update && apt-get install -y libpq-dev python3-dev
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
    startCommand: gunicorn social_media_api.wsgi:application --workers 4 --threads 2 --timeout 120 --log-level info
    healthCheckPath: /healthz/
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: social_media_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: social-media-cache
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.13.1
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: social_media_api.settings
      - key: PYTHONPATH
        value: .
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://*.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 75
      targetCPUPercent: 75

  - type: redis
    name: social-media-cache
    plan: starter
    maxmemoryPolicy: noeviction
    ipAllowList: [] # All IPs are allowed

databases:
  - name: social_media_db
    databaseName: social_media_db
    plan: starter
    ipAllowList: []
