services:
  - type: web
    name: social-media-api
    env: python
    plan: starter
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
      python create_superuser.py
    startCommand: |
      python manage.py migrate --noinput
      gunicorn social_media_api.wsgi:application --workers 2 --timeout 120 --max-requests 1000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: DATABASE_URL
        fromDatabase:
          name: social_media_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: social_media_api.settings
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@example.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true

databases:
  - name: social_media_db
    databaseName: social_media_db
    plan: starter
