services:
  - type: web
    name: social-media-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --chdir social_media_api wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: social_media_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHONPATH
        value: .
      - key: DJANGO_SETTINGS_MODULE
        value: social_media_api.settings

databases:
  - name: social_media_db
    databaseName: social_media_db
    plan: free
