services:
  - type: web
    name: social-media-api
    env: python
    plan: starter
    buildCommand: |
      # Install system dependencies for Pillow
      apt-get update
      apt-get install -y --no-install-recommends \
        python3-dev \
        python3-pip \
        python3-setuptools \
        python3-wheel \
        gcc \
        libjpeg-dev \
        libpng-dev \
        libtiff-dev \
        libfreetype6-dev \
        liblcms2-dev \
        libwebp-dev \
        zlib1g-dev
      # Install Python packages
      pip install --upgrade pip
      pip install wheel
      pip install Pillow==10.1.0
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: |
      python manage.py migrate --noinput
      gunicorn social_media_api.wsgi:application --workers 2 --timeout 120 --max-requests 1000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        fromDatabase:
          name: social_media_db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: social_media_api.settings
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@example.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true
    disk:
      name: media
      mountPath: /opt/render/project/src/media
      sizeGB: 1

databases:
  - name: social_media_db
    plan: starter
