services:
  - type: web
    name: social-media-api
    env: python
    plan: starter
    buildCommand: |
      python -m pip install --upgrade pip
      pip install wheel
      pip install setuptools --upgrade
      pip install --no-cache-dir -r requirements.txt
    startCommand: |
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
      gunicorn social_media_api.wsgi:application --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        fromDatabase:
          name: social_media_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: social_media_api.settings
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHONUNBUFFERED
        value: "1"

databases:
  - name: social_media_db
    databaseName: social_media_db
    plan: starter
