services:
  - type: web
    name: social-media-api
    env: python
    buildCommand: |
      apt-get update && apt-get install -y libpq-dev python3-dev
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
    startCommand: gunicorn social_media_api.wsgi:application --log-level debug
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: social_media_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.13.1
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: social_media_api.settings
      - key: PYTHONPATH
        value: .
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://*.onrender.com"

databases:
  - name: social_media_db
    databaseName: social_media_db
    plan: free
