services:
  - type: web
    name: social-media-api
    env: python
    plan: starter
    buildCommand: |
      # Install build essentials
      apt-get update && apt-get install -y build-essential python3-dev
      # Upgrade pip in a safe way
      python -m pip install --upgrade pip
      # Install requirements
      pip install -r requirements.txt
    startCommand: |
      python manage.py migrate --noinput
      gunicorn social_media_api.wsgi:application --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        fromDatabase:
          name: social_media_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: social_media_api.settings
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PIP_NO_CACHE_DIR
        value: "1"

databases:
  - name: social_media_db
    databaseName: social_media_db
    plan: starter
