services:
  - type: web
    name: social-media-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
    startCommand: gunicorn social_media_api.wsgi:application --log-level debug --timeout 120 --chdir /opt/render/project/src
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: social_media_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: social_media_api.settings
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DEBUG
        value: "True"

databases:
  - name: social_media_db
    databaseName: social_media_db
    plan: free
