services:
  - type: web
    name: social-media-api
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      # Update package lists
      apt-get update
      # Install system dependencies
      apt-get install -y \
        python3-pip \
        python3-dev \
        python3-setuptools \
        python3-wheel \
        gcc \
        libpq-dev \
        libjpeg-dev \
        libpng-dev
      # Upgrade pip and install wheel
      python -m pip install --upgrade pip
      python -m pip install wheel
      # Install project dependencies
      pip install -r requirements.txt
      # Run Django commands
      python manage.py collectstatic --noinput
    startCommand: gunicorn social_media_api.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DATABASE_URL
        fromDatabase:
          name: social_media_db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: social_media_api.settings
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_DEBUG
        value: "false"
    disk:
      name: media
      mountPath: /opt/render/project/src/media
      sizeGB: 1
    autoDeploy: true
    healthCheckPath: /api/healthz/

databases:
  - name: social_media_db
    region: oregon
    plan: starter
    ipAllowList: []
