services:
  - type: web
    name: social-media-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: |
      pwd && ls -la && 
      PYTHONPATH=/opt/render/project/src gunicorn social_media_api.wsgi:application --log-level debug
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: social_media_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: social_media_api.settings
      - key: DEBUG
        value: "True"

databases:
  - name: social_media_db
    databaseName: social_media_db
    plan: free
