# Generated by Django 5.1.4 on 2025-01-02 15:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text='Cover photo - Maximum size 5MB', max_length=255, null=True, upload_to=api.models.user_cover_photo_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture - Maximum size 5MB', max_length=255, null=True, upload_to=api.models.user_profile_picture_path),
        ),
    ]
